-- ⚠️ DEPRECATED - DO NOT USE THIS FILE
-- 
-- This file is outdated and NOT synchronized with schema.prisma
-- Use Prisma migrations instead:
--
-- npx prisma db push        (development)
-- npx prisma migrate deploy (production)
--
-- Migrations are in: ./migrations/
-- Latest migration: 2_add_email_verification_token/migration.sql
--
-- WARNING: Running this file will CORRUPT your database!
-- The correct way to initialize the database is:
-- 1. cd backend
-- 2. npx prisma db push  (or prisma migrate deploy)
-- 3. Done!

-- DO NOT RUN THE SQL BELOW - USE PRISMA INSTEAD
