name: barbweb
services:
  - name: barbweb
    github:
      branch: master
      repo: DAMSanti/BarbWeb
    build_command: cd /workspace/backend && npm install && npm run build
    run_command: cd /workspace/backend && npm start
    envs:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
      - key: VITE_API_URL
        value: https://${APP_DOMAIN}
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: ${VITE_STRIPE_PUBLISHABLE_KEY}
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
      - key: EMAIL_FROM
        value: ${EMAIL_FROM}
      - key: LAWYER_EMAIL
        value: ${LAWYER_EMAIL}
    http_port: 3000

databases:
  - name: postgres-db
    engine: PG
    version: "15"
    production: true
