name: barbweb
services:
- name: backend
  github:
    branch: master
    repo: DAMSanti/BarbWeb
  source_dir: server
  build_command: npm run build
  run_command: node dist/index.js
  envs:
  - key: PORT
    value: "3000"
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: FRONTEND_URL
    value: ${FRONTEND_URL}
  http_port: 3000

- name: frontend
  github:
    branch: master
    repo: DAMSanti/BarbWeb
  build_command: tsc && vite build
  run_command: npm run preview
  envs:
  - key: VITE_API_URL
    value: ${BACKEND_URL}
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    value: ${VITE_STRIPE_PUBLISHABLE_KEY}
  http_port: 5173
