name: barbweb
services:
- name: backend
  github:
    branch: master
    repo: DAMSanti/BarbWeb
  build_command: npm install --legacy-peer-deps && npm run build:frontend && npm run build:backend
  run_command: cd /workspace/backend && node dist/index.js
  envs:
  - key: PORT
    value: "3000"
  - key: NODE_ENV
    value: production
  - key: GEMINI_API_KEY
    value: ${GEMINI_API_KEY}
  - key: FRONTEND_URL
    value: ${FRONTEND_URL}
  - key: VITE_API_URL
    value: ${BACKEND_URL}
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    value: ${VITE_STRIPE_PUBLISHABLE_KEY}
  http_port: 3000
